version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: backend_prowad
    ports:
      - "8000:8000"
    # dns:              
    #   - 8.8.8.8       
    #   - 8.8.4.4        
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules